'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FERRETERIAEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FERRETERIAEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property categoria() As DbSet(Of categoria)
    Public Overridable Property cliente() As DbSet(Of cliente)
    Public Overridable Property detalle() As DbSet(Of detalle)
    Public Overridable Property producto() As DbSet(Of producto)
    Public Overridable Property tipo_usuario() As DbSet(Of tipo_usuario)
    Public Overridable Property usuario() As DbSet(Of usuario)
    Public Overridable Property venta() As DbSet(Of venta)
    Public Overridable Property MSreplication_queue() As DbSet(Of MSreplication_queue)
    Public Overridable Property MSrepl_queuedtraninfo() As DbSet(Of MSrepl_queuedtraninfo)
    Public Overridable Property MSreplication_objects() As DbSet(Of MSreplication_objects)
    Public Overridable Property MSreplication_subscriptions() As DbSet(Of MSreplication_subscriptions)
    Public Overridable Property MSsubscription_agents() As DbSet(Of MSsubscription_agents)
    Public Overridable Property MSsubscription_articlecolumns() As DbSet(Of MSsubscription_articlecolumns)
    Public Overridable Property MSsubscription_articles() As DbSet(Of MSsubscription_articles)
    Public Overridable Property MSsubscription_properties() As DbSet(Of MSsubscription_properties)

    Public Overridable Function ControProd(estado As Nullable(Of Integer), stockminimo As Nullable(Of Integer)) As ObjectResult(Of ControProd_Result)
        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("estado", estado), New ObjectParameter("estado", GetType(Integer)))

        Dim stockminimoParameter As ObjectParameter = If(stockminimo.HasValue, New ObjectParameter("stockminimo", stockminimo), New ObjectParameter("stockminimo", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ControProd_Result)("ControProd", estadoParameter, stockminimoParameter)
    End Function

    Public Overridable Function reporte_prod(estado As Nullable(Of Integer), minstock As Nullable(Of Integer)) As ObjectResult(Of reporte_prod_Result)
        Dim estadoParameter As ObjectParameter = If(estado.HasValue, New ObjectParameter("estado", estado), New ObjectParameter("estado", GetType(Integer)))

        Dim minstockParameter As ObjectParameter = If(minstock.HasValue, New ObjectParameter("minstock", minstock), New ObjectParameter("minstock", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_prod_Result)("reporte_prod", estadoParameter, minstockParameter)
    End Function

    Public Overridable Function reporte_producto() As ObjectResult(Of reporte_producto_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_producto_Result)("reporte_producto")
    End Function

    Public Overridable Function reporte_usuario() As ObjectResult(Of reporte_usuario_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_usuario_Result)("reporte_usuario")
    End Function

    Public Overridable Function reporte_ventas(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of reporte_ventas_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reporte_ventas_Result)("reporte_ventas", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function reportefechas(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of reportefechas_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of reportefechas_Result)("reportefechas", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function sp_comprobante() As ObjectResult(Of sp_comprobante_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_comprobante_Result)("sp_comprobante")
    End Function

    Public Overridable Function sp_compUna(idVenta As Nullable(Of Integer)) As ObjectResult(Of sp_compUna_Result)
        Dim idVentaParameter As ObjectParameter = If(idVenta.HasValue, New ObjectParameter("idVenta", idVenta), New ObjectParameter("idVenta", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_compUna_Result)("sp_compUna", idVentaParameter)
    End Function

    Public Overridable Function sp_unaVenta111() As ObjectResult(Of sp_unaVenta111_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_unaVenta111_Result)("sp_unaVenta111")
    End Function

    Public Overridable Function sp_unEmpleadoVentas(idEmpleado As Nullable(Of Integer), fechaDesde As Nullable(Of Date), fechaHasta As Nullable(Of Date)) As ObjectResult(Of sp_unEmpleadoVentas_Result)
        Dim idEmpleadoParameter As ObjectParameter = If(idEmpleado.HasValue, New ObjectParameter("idEmpleado", idEmpleado), New ObjectParameter("idEmpleado", GetType(Integer)))

        Dim fechaDesdeParameter As ObjectParameter = If(fechaDesde.HasValue, New ObjectParameter("fechaDesde", fechaDesde), New ObjectParameter("fechaDesde", GetType(Date)))

        Dim fechaHastaParameter As ObjectParameter = If(fechaHasta.HasValue, New ObjectParameter("fechaHasta", fechaHasta), New ObjectParameter("fechaHasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_unEmpleadoVentas_Result)("sp_unEmpleadoVentas", idEmpleadoParameter, fechaDesdeParameter, fechaHastaParameter)
    End Function

    Public Overridable Function sp_Venta() As ObjectResult(Of sp_Venta_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_Venta_Result)("sp_Venta")
    End Function

    Public Overridable Function sp_ventaPorfecha(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of sp_ventaPorfecha_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_ventaPorfecha_Result)("sp_ventaPorfecha", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function sp_ventaPorfecha1(fecha As Nullable(Of Date), fecha2 As Nullable(Of Date)) As ObjectResult(Of sp_ventaPorfecha1_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim fecha2Parameter As ObjectParameter = If(fecha2.HasValue, New ObjectParameter("fecha2", fecha2), New ObjectParameter("fecha2", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_ventaPorfecha1_Result)("sp_ventaPorfecha1", fechaParameter, fecha2Parameter)
    End Function

    Public Overridable Function Vdeldia(fecha As Nullable(Of Date)) As ObjectResult(Of Vdeldia_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Vdeldia_Result)("Vdeldia", fechaParameter)
    End Function

    Public Overridable Function VentasDelDia(fecha As Nullable(Of Date)) As ObjectResult(Of VentasDelDia_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of VentasDelDia_Result)("VentasDelDia", fechaParameter)
    End Function

    Public Overridable Function sp_VentasPorUsuarioYFecha(usuario As String, fechaDesde As Nullable(Of Date), fechaHasta As Nullable(Of Date)) As ObjectResult(Of sp_VentasPorUsuarioYFecha_Result)
        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Dim fechaDesdeParameter As ObjectParameter = If(fechaDesde.HasValue, New ObjectParameter("fechaDesde", fechaDesde), New ObjectParameter("fechaDesde", GetType(Date)))

        Dim fechaHastaParameter As ObjectParameter = If(fechaHasta.HasValue, New ObjectParameter("fechaHasta", fechaHasta), New ObjectParameter("fechaHasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_VentasPorUsuarioYFecha_Result)("sp_VentasPorUsuarioYFecha", usuarioParameter, fechaDesdeParameter, fechaHastaParameter)
    End Function

    Public Overridable Function unEmpleadoVentas2(usuario As String, fechaDesde As Nullable(Of Date), fechaHasta As Nullable(Of Date)) As ObjectResult(Of unEmpleadoVentas2_Result)
        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Dim fechaDesdeParameter As ObjectParameter = If(fechaDesde.HasValue, New ObjectParameter("fechaDesde", fechaDesde), New ObjectParameter("fechaDesde", GetType(Date)))

        Dim fechaHastaParameter As ObjectParameter = If(fechaHasta.HasValue, New ObjectParameter("fechaHasta", fechaHasta), New ObjectParameter("fechaHasta", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of unEmpleadoVentas2_Result)("unEmpleadoVentas2", usuarioParameter, fechaDesdeParameter, fechaHastaParameter)
    End Function

    Public Overridable Function sp_MostrarProductoPorCodigo(codigoProducto As Nullable(Of Integer)) As ObjectResult(Of sp_MostrarProductoPorCodigo_Result)
        Dim codigoProductoParameter As ObjectParameter = If(codigoProducto.HasValue, New ObjectParameter("codigoProducto", codigoProducto), New ObjectParameter("codigoProducto", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_MostrarProductoPorCodigo_Result)("sp_MostrarProductoPorCodigo", codigoProductoParameter)
    End Function

    Public Overridable Function MostrarProductoPorCodigo(cod_producto As Nullable(Of Integer)) As ObjectResult(Of MostrarProductoPorCodigo_Result)
        Dim cod_productoParameter As ObjectParameter = If(cod_producto.HasValue, New ObjectParameter("cod_producto", cod_producto), New ObjectParameter("cod_producto", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of MostrarProductoPorCodigo_Result)("MostrarProductoPorCodigo", cod_productoParameter)
    End Function

    Public Overridable Function MostrarProductosPorCodigo1(codigoProducto As Nullable(Of Integer)) As ObjectResult(Of MostrarProductosPorCodigo1_Result)
        Dim codigoProductoParameter As ObjectParameter = If(codigoProducto.HasValue, New ObjectParameter("codigoProducto", codigoProducto), New ObjectParameter("codigoProducto", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of MostrarProductosPorCodigo1_Result)("MostrarProductosPorCodigo1", codigoProductoParameter)
    End Function

    Public Overridable Function mostrarTOP10masvendidos(fecha_inicio As Nullable(Of Date), fecha_final As Nullable(Of Date)) As ObjectResult(Of mostrarTOP10masvendidos_Result)
        Dim fecha_inicioParameter As ObjectParameter = If(fecha_inicio.HasValue, New ObjectParameter("fecha_inicio", fecha_inicio), New ObjectParameter("fecha_inicio", GetType(Date)))

        Dim fecha_finalParameter As ObjectParameter = If(fecha_final.HasValue, New ObjectParameter("fecha_final", fecha_final), New ObjectParameter("fecha_final", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of mostrarTOP10masvendidos_Result)("mostrarTOP10masvendidos", fecha_inicioParameter, fecha_finalParameter)
    End Function

End Class
