'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSreplication_queue
    Public Property publisher As String
    Public Property publisher_db As String
    Public Property publication As String
    Public Property tranid As String
    Public Property data As Byte()
    Public Property datalen As Nullable(Of Integer)
    Public Property commandtype As Nullable(Of Integer)
    Public Property insertdate As Nullable(Of Date)
    Public Property orderkey As Long
    Public Property cmdstate As Boolean

End Class
