'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSreplication_subscriptions
    Public Property publisher As String
    Public Property publisher_db As String
    Public Property publication As String
    Public Property independent_agent As Boolean
    Public Property subscription_type As Integer
    Public Property distribution_agent As String
    Public Property time As Date
    Public Property description As String
    Public Property transaction_timestamp As Byte()
    Public Property update_mode As Byte
    Public Property agent_id As Byte()
    Public Property subscription_guid As Byte()
    Public Property subid As Byte()
    Public Property immediate_sync As Boolean

End Class
