'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSsubscription_articles
    Public Property agent_id As Integer
    Public Property artid As Integer
    Public Property article As String
    Public Property dest_table As String
    Public Property owner As String
    Public Property cft_table As String

End Class
