'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSsubscription_properties
    Public Property publisher As String
    Public Property publisher_db As String
    Public Property publication As String
    Public Property publication_type As Integer
    Public Property publisher_login As String
    Public Property publisher_password As String
    Public Property publisher_security_mode As Integer
    Public Property distributor As String
    Public Property distributor_login As String
    Public Property distributor_password As String
    Public Property distributor_security_mode As Integer
    Public Property ftp_address As String
    Public Property ftp_port As Nullable(Of Integer)
    Public Property ftp_login As String
    Public Property ftp_password As String
    Public Property alt_snapshot_folder As String
    Public Property working_directory As String
    Public Property use_ftp As Boolean
    Public Property dts_package_name As String
    Public Property dts_package_password As String
    Public Property dts_package_location As Integer
    Public Property enabled_for_syncmgr As Boolean
    Public Property offload_agent As Boolean
    Public Property offload_server As String
    Public Property dynamic_snapshot_location As String
    Public Property use_web_sync As Boolean
    Public Property internet_url As String
    Public Property internet_login As String
    Public Property internet_password As String
    Public Property internet_security_mode As Integer
    Public Property internet_timeout As Integer
    Public Property hostname As String
    Public Property publisherlink As String
    Public Property publisherlinkuser As String
    Public Property job_step_uid As Nullable(Of System.Guid)

End Class
